version: '3.8'

services:
  web:
    build: .
    ports:
      - "4321:4321"
    environment:
      - HOST=0.0.0.0
      - PORT=4321
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4321"]
      interval: 30s
      timeout: 10s
      retries: 3
